on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: run tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download mods
      run: go mod download
    - name: Run tests
      run: go test -v ./...
    - name: Install package locally
      run: go install .
